### ISSUE TITLE
404 message 

### ISSUE THREAD

**Issue by matthewgutz** [tronikos/opower-hacs#2]
Followed instructions for HACs install, getting the following error
![image](https://user-images.githubusercontent.com/73972514/236630753-d32200e8-4e1f-45ff-9f68-3547b8217bec.png)

**Comment by felixhng** [comment]
Same, I'm also affected. Worked fine yesterday

**Comment by tronikos** [comment]
Same here. It has been working fine for me for the past month or so. I'll try to fix it tonight or tomorrow.

**Comment by tronikos** [comment]
Going to energy usage -> projected bill on the website I get:
```
Bill forecast
This information is not available.
```

The underlying json response is:
```
{"error":{"details":"Some accounts have no forecast data as of date Sun May 07 01:36:12 EDT 2023 .","serviceErrorCode":"INSUFFICIENT_DATA"}}
```

I also noticed the last day the website (and the integration) has data is April 29.

There seems to be an issue on PG&E or Opower end. Hopefully they will fix it soon.

**Comment by ampersandru** [comment]
Mirroring the same issue and my PGE account also only goes up to April 29th

**Comment by sheyman1** [comment]
Problem for me too, showing 404 message=Not Found on the integration.

**Comment by ampersandru** [comment]
seems widespread and still no fix. Typical PG&E
https://www.reddit.com/r/bayarea/comments/13danh6/pge_energy_use_and_bill_projection_quit_working/

**Comment by ampersandru** [comment]
looks like its working again and theres more updated usage

**Comment by matthewgutz** [comment]
Initially ran into this error when re-enabling the integration:
![image](https://github.com/tronikos/opower-hacs/assets/73972514/de89be10-d826-4ff6-9c26-f074ff0ab06c)
Deleted the integration and saw on HACs that it had been updated to v0.0.3. Updated and restarted HA.
Added integration with account info. Initially was showing the below error:
![image](https://github.com/tronikos/opower-hacs/assets/73972514/15bb1ff3-05ec-4e5d-bf38-a4db160fc53b)

However after waiting a couple minutes it started to work.
Thanks for the Integration!
